---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.9-stretch

inputs:
  - name: cloudformation-resource

outputs:
  - name: out

run:
  path: bash
  args: ["cloudformation-resource/ci/scripts/build.sh", "out"]
