---
resources:
  - name: cloudformation-resource
    type: git
    source:
      uri: https://github.com/ci-pipeline/cloudformation-resource.git
      branch: master
  - name: cloudformation-resource-image
    type: docker-image
    source:
      repository: pipelineci/cloudformation-resource
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

jobs:
  - name: cloudformation-resource-build
    plan:
      - get: cloudformation-resource
        trigger: true
      - aggregate:
        - task: build-check
          file: cloudformation-resource/ci/tasks/build-check.yml
        - task: build-in
          file: cloudformation-resource/ci/tasks/build-in.yml
        - task: build-out
          file: cloudformation-resource/ci/tasks/build-out.yml
      - put: cloudformation-resource-image
        params:
          build: cloudformation-resource
