---
resources:
  - name: cloudformation-resource
    type: git
    source:
      uri: https://github.com/ci-pipeline/cloudformation-resource.git
      branch: master
  - name: cloudformation-resource-image
    type: docker-image
    source:
      repository: pipelineci/cloudformation-resource
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

jobs:
  - name: cloudformation-resource-build
    plan:
      - get: cloudformation-resource
        trigger: true
      - aggregate:
        - task: build-check
          file: cloudformation-resource/ci/tasks/build-check.yml
        - task: build-in
          file: cloudformation-resource/ci/tasks/build-in.yml
        - task: build-out
          file: cloudformation-resource/ci/tasks/build-out.yml
      - task: check-files
        config:
          platform: linux
          inputs:
            - name: check
            - name: in
            - name: out
          image_resource:
            type: docker-image
            source:
              repository: alpine
          run:
            path: sh
            args:
              - -c
              - |
                ls -lah
                ls -lah in
      - put: cloudformation-resource-image
        params:
          build: ./
          dockerfile: cloudformation-resource/Dockerfile
